version: '3'
services:
  okty:
    image: 'node:8-alpine'
    container_name: 'okty-app'
    ports:
      - '4200:4200'
    volumes:
      - './okty:/app'
    working_dir: '/app'
    command: ['sh', '-c', 'npm install && npm start']
  config:
    image: 'node:8-alpine'
    container_name: 'okty-config-app'
    ports:
      - '3000:3000'
    volumes:
      - './okty-config:/app'
    working_dir: '/app'
    command: ['sh', '-c', 'npm install && npm start']
